### ISSUE TITLE
Not Building Bot

### ISSUE THREAD

**Issue by devilxsam** [bipinkrish/Link-Bypasser-Bot#112]
My Logs

[1] 1960
Traceback (most recent call last):
  File "/home/samyiixx/Bots/LBB/app.py", line 2, in <module>
    import bypasser
  File "/home/samyiixx/Bots/LBB/bypasser.py", line 12, in <module>
    import ddl
  File "/home/samyiixx/Bots/LBB/ddl.py", line 17, in <module>
    with open('config.json', 'r') as f: DATA = load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 15 column 5 (char 811)
Traceback (most recent call last):
  File "/home/samyiixx/Bots/LBB/main.py", line 10, in <module>
    import bypasser
  File "/home/samyiixx/Bots/LBB/bypasser.py", line 12, in <module>
    import ddl
  File "/home/samyiixx/Bots/LBB/ddl.py", line 17, in <module>
    with open('config.json', 'r') as f: DATA = load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 15 column 5 (char 811)
[1]+  Exit 1                  python3 app.py

**Comment by bipinkrish** [comment]
You have to follow the JSON format rules
