### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by awdealofficial** [bipinkrish/Link-Bypasser-Bot#39]
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import bypasser
  File "/root/link/bypasser.py", line 16, in <module>
    import PyBypass
  File "/usr/local/lib/python3.7/site-packages/PyBypass/__init__.py", line 2, in <module>
    from PyBypass.main import bypass
  File "/usr/local/lib/python3.7/site-packages/PyBypass/main.py", line 4, in <module>
    from PyBypass.Filehoster import *
  File "/usr/local/lib/python3.7/site-packages/PyBypass/Filehoster/__init__.py", line 2, in <module>
    from .anonfiles_bypass import anonfiles_bypass
  File "/usr/local/lib/python3.7/site-packages/PyBypass/Filehoster/anonfiles_bypass.py", line 11
    if (dlurl := soup.find(id="download-url")): return dlurl["href"]
              ^
SyntaxError: invalid syntax

**Comment by bipinkrish** [comment]
Update the python version
